Use libayatana-appindicator in polychromatic
Summary:
Use libayatana-indicator in polychromatic.

Depends on D11707.

Test Plan:
Tray icon still shows. Menu works.

Note: while this patch correctly makes polychromatic use AyatanaAppIndicator in `polychromatic-tray-applet`, `polychromatic-controller` fails to start because of:
```
  File "/usr/bin/polychromatic-controller", line 37, in <module>
    from platform import linux_distribution
ImportError: cannot import name 'linux_distribution' from 'platform' (/usr/lib/python3.9/platform.py)
```

It seems it's not compatible with Python 3.9. After all, this is an old release of polychromatic.

Reviewers: #triage_team, JoshStrobl

Reviewed By: #triage_team, JoshStrobl

Subscribers: JoshStrobl

Differential Revision: https://dev.getsol.us/D11731